`timescale 1ns / 1ps
`include "hdmi/svo_defines.vh"

// Draws the survival timer, the level, the kill streak, and a small lit box for
// each button. The button boxes are there so you can check the wiring on screen
// without a debugger, which saved us more than once during the build.
module ui_layer #(
	`SVO_DEFAULT_PARAMS
) (
	input clk,
	input resetn,

	input [11:0] timer_bcd,
	input [3:0] game_level,
	input [5:0] kill_streak,
	input skill_ready,
	input skill_on,
	input game_idle,
	input game_over,

	input btn_up,
	input btn_down,
	input btn_left,
	input btn_right,
	input btn_skill,

	// input stream from previous layer
	input in_axis_tvalid,
	output in_axis_tready,
	input [SVO_BITS_PER_PIXEL-1:0] in_axis_tdata,
	input [0:0] in_axis_tuser,

	// output stream to next layer
	output out_axis_tvalid,
	input out_axis_tready,
	output [SVO_BITS_PER_PIXEL-1:0] out_axis_tdata,
	output [0:0] out_axis_tuser
);
`SVO_DECLS

localparam UI_TOP = 416;
localparam UI_TOP_BAR_H = 16;   // dark bar above the background image band

// Timer digits are 24 by 48 each, sitting just under the top bar in the sky.
// Three digits and two gaps come to 84 px, so they start at 278 to land centred.
localparam DIGIT_Y = 24;
localparam DIGIT_W = 24;
localparam DIGIT_H = 48;
localparam DIGIT_GAP = 6;
localparam TIMER_X = 278;

// Small text is half the size of the timer, so 12 by 24 per character.
localparam SMALL_W     = 12;   // 6 * 2
localparam SMALL_H     = 24;   // 12 * 2
localparam SMALL_STRIDE = 14;  // (6 + 1) * 2

// LEVEL sits on the left, the kill streak on the right, the timer in the middle.
localparam LEVEL_X     = 24;
localparam LEVEL_Y     = 36;
localparam LEVEL_NUM_X = LEVEL_X + 5 * SMALL_STRIDE + 8;

// The kill streak is two digits in the top right corner.
localparam STREAK_X    = 576;
localparam STREAK_Y    = 36;

// Glyph numbers inside res_font.mem, generated by .vscode/bitmap2mem.ps1.
// Digits run 0 to 9 and the letters start at 11.
localparam [4:0] GL_E = 5'd13;
localparam [4:0] GL_L = 5'd22;
localparam [4:0] GL_V = 5'd23;

// Every character starts life as a 6x12 glyph and is scaled up from there
localparam FONT_W = 6;
localparam FONT_H = 12;

// Button indicator boxes, one per button, drawn inside the 16 px top bar.
localparam IND_X = 8;
localparam IND_Y = 2;
localparam IND_W = 16;
localparam IND_H = 12;
localparam IND_GAP = 8;

localparam [23:0] UI_BG_RGB     = 24'h181818;
localparam [23:0] TIMER_RGB     = 24'hFFFFFF;
localparam [23:0] LEVEL_RGB     = 24'h20EAFF;   // amber, so it reads apart from the timer
localparam [23:0] STREAK_RGB    = 24'hFFFFFF;   // white while charging
localparam [23:0] STREAK_RDY_RGB= 24'h40FF40;   // green once the skill is ready
localparam [23:0] STREAK_ON_RGB = 24'h20A0FF;   // orange while the skill is running
localparam [23:0] INDICATOR_RGB = 24'h20FF40;

reg [`SVO_XYBITS-1:0] hcursor, vcursor;
reg [4:0] blink_cnt;
reg blink_on;

wire fire = in_axis_tvalid && in_axis_tready;
wire [`SVO_XYBITS-1:0] pixel_x = in_axis_tuser[0] ? 0 : hcursor;
wire [`SVO_XYBITS-1:0] pixel_y = in_axis_tuser[0] ? 0 : vcursor;

wire [3:0] timer_d2 = timer_bcd[11:8];
wire [3:0] timer_d1 = timer_bcd[7:4];
wire [3:0] timer_d0 = timer_bcd[3:0];

// The streak never goes past 20, so two compares are cheaper than a real BCD
// converter and do exactly the same job here.
reg [3:0] streak_tens;
reg [3:0] streak_ones;
always @(*) begin
	if (kill_streak >= 6'd20) begin
		streak_tens = 4'd2;
		streak_ones = kill_streak - 6'd20;
	end else if (kill_streak >= 6'd10) begin
		streak_tens = 4'd1;
		streak_ones = kill_streak - 6'd10;
	end else begin
		streak_tens = 4'd0;
		streak_ones = kill_streak[3:0];
	end
end

// For the three digit timer, work out which column this pixel falls in and how
// far into it, packed as hit, column, then local x.
function [7:0] big_col;
	input [`SVO_XYBITS-1:0] px;
	input [`SVO_XYBITS-1:0] base;
	integer i;
	reg [`SVO_XYBITS-1:0] dleft;
	reg [4:0] lx;
	begin
		big_col = 8'd0;
		for (i = 0; i < 3; i = i + 1) begin
			dleft = base + i * (DIGIT_W + DIGIT_GAP);
			if (px >= dleft && px < dleft + DIGIT_W) begin
				lx = px - dleft;
				big_col = {1'b1, i[1:0], lx};
			end
		end
	end
endfunction

// Same idea for the five letters of LEVEL, packed as hit, index, then local x.
function [7:0] small_col;
	input [`SVO_XYBITS-1:0] px;
	input [`SVO_XYBITS-1:0] base;
	integer i;
	reg [`SVO_XYBITS-1:0] cleft;
	reg [3:0] lx;
	begin
		small_col = 8'd0;
		for (i = 0; i < 5; i = i + 1) begin
			cleft = base + i * SMALL_STRIDE;
			if (px >= cleft && px < cleft + SMALL_W) begin
				lx = px - cleft;
				small_col = {1'b1, i[2:0], lx};
			end
		end
	end
endfunction

// Work out which glyph this pixel lands in, which character that glyph shows,
// and where inside the 6x12 font it sits. The big text is scaled 4 times and the
// LEVEL text twice, both of which are shifts rather than real division.
reg        glyph_hit;
reg        is_level;
reg        is_streak;
reg [4:0]  glyph;
reg [2:0]  src_x;
reg [3:0]  src_y;

reg [7:0]  tcol;
reg [7:0]  lcol;
reg [4:0]  lx_sel;
reg [`SVO_XYBITS-1:0] ly_big;
reg [`SVO_XYBITS-1:0] ly_small;

wire in_level_row = pixel_y >= LEVEL_Y && pixel_y < LEVEL_Y + SMALL_H;

always @(*) begin
	glyph_hit = 1'b0;
	is_level  = 1'b0;
	is_streak = 1'b0;
	glyph     = 5'd0;
	src_x     = 3'd0;
	src_y     = 4'd0;
	lx_sel    = 5'd0;
	ly_big    = 0;
	ly_small  = 0;

	tcol = big_col(pixel_x, TIMER_X);
	lcol = small_col(pixel_x, LEVEL_X);

	// The three big timer digits
	if (pixel_y >= DIGIT_Y && pixel_y < DIGIT_Y + DIGIT_H && tcol[7]) begin
		ly_big = pixel_y - DIGIT_Y;
		glyph_hit = 1'b1;
		lx_sel = tcol[4:0];
		case (tcol[6:5])
			2'd0: glyph = {1'b0, timer_d2};
			2'd1: glyph = {1'b0, timer_d1};
			default: glyph = {1'b0, timer_d0};
		endcase
		src_x = lx_sel[4:2];
		src_y = ly_big[5:2];
	end

	// The word LEVEL itself
	else if (in_level_row && lcol[7]) begin
		ly_small = pixel_y - LEVEL_Y;
		glyph_hit = 1'b1;
		is_level  = 1'b1;
		case (lcol[6:4])
			3'd0: glyph = GL_L;
			3'd1: glyph = GL_E;
			3'd2: glyph = GL_V;
			3'd3: glyph = GL_E;
			default: glyph = GL_L;
		endcase
		src_x = {1'b0, lcol[3:1]};
		src_y = ly_small[4:1];
	end

	// The level number itself
	else if (in_level_row &&
			 pixel_x >= LEVEL_NUM_X && pixel_x < LEVEL_NUM_X + SMALL_W) begin
		ly_small = pixel_y - LEVEL_Y;
		glyph_hit = 1'b1;
		is_level  = 1'b1;
		glyph = {1'b0, game_level};
		src_x = (pixel_x - LEVEL_NUM_X) >> 1;
		src_y = ly_small[4:1];
	end

	// Kill streak, two digits in the top right
	else if (pixel_y >= STREAK_Y && pixel_y < STREAK_Y + SMALL_H &&
			 pixel_x >= STREAK_X && pixel_x < STREAK_X + SMALL_STRIDE + SMALL_W) begin
		ly_small = pixel_y - STREAK_Y;
		if (pixel_x < STREAK_X + SMALL_W) begin
			glyph_hit = 1'b1;
			is_streak = 1'b1;
			glyph = {1'b0, streak_tens};
			src_x = (pixel_x - STREAK_X) >> 1;
			src_y = ly_small[4:1];
		end else if (pixel_x >= STREAK_X + SMALL_STRIDE) begin
			glyph_hit = 1'b1;
			is_streak = 1'b1;
			glyph = {1'b0, streak_ones};
			src_x = (pixel_x - STREAK_X - SMALL_STRIDE) >> 1;
			src_y = ly_small[4:1];
		end
	end
end

// The streak changes colour so a glance tells you whether the skill is still
// charging, ready to press, or already running.
wire [23:0] streak_colour = skill_on    ? STREAK_ON_RGB :
							skill_ready ? STREAK_RDY_RGB :
										  STREAK_RGB;

// res_font.mem holds digits and letters together, so the timer, the word LEVEL
// and the streak all come out of this one ROM.
wire [8:0] font_addr = {glyph, src_y};
wire [5:0] font_row;

rom #(
	.DATA_WIDTH(6),
	.ADDR_WIDTH(9),
	.DEPTH(512),
	.INIT_FILE("src/assets/res_font.mem")
) u_font_rom (
	.clk(clk),
	.addr(font_addr),
	.data(font_row)
);

// One box per button, lit while that button is held. They sit left to right in
// the top bar in the order a, w, s, d, skill.
wire [4:0] btn_bus = {btn_skill, btn_right, btn_down, btn_up, btn_left};

integer ind_i;
reg btn_indicator;

always @(*) begin
	btn_indicator = 1'b0;

	for (ind_i = 0; ind_i < 5; ind_i = ind_i + 1) begin
		if (btn_bus[ind_i] &&
			pixel_y >= IND_Y && pixel_y < IND_Y + IND_H &&
			pixel_x >= IND_X + ind_i * (IND_W + IND_GAP) &&
			pixel_x <  IND_X + ind_i * (IND_W + IND_GAP) + IND_W) begin
			btn_indicator = 1'b1;
		end
	end
end

// The timer blinks before the game starts and after it ends, so a number sitting
// still on screen always means you are actually playing.
wire blinking = game_idle || game_over;
wire timer_on = !blinking || blink_on;
wire in_ui = (pixel_y >= UI_TOP) || (pixel_y < UI_TOP_BAR_H);

// The font ROM answers a cycle late, so everything decided above waits a cycle
// to stay lined up with its pixel.
reg glyph_hit_d;
reg is_level_d;
reg is_streak_d;
reg [23:0] streak_colour_d;
reg [2:0] src_x_d;
reg [SVO_BITS_PER_PIXEL-1:0] bg_d;
reg [0:0] tuser_d;
reg tvalid_d;
reg timer_on_d;
reg btn_ind_d, in_ui_d;

assign in_axis_tready  = out_axis_tready;
assign out_axis_tvalid = tvalid_d;
assign out_axis_tuser  = tuser_d;

wire glyph_on = glyph_hit_d & font_row[3'd5 - src_x_d];   // top bit is the left column

assign out_axis_tdata =
	btn_ind_d                                ? INDICATOR_RGB :
	(glyph_on && is_level_d)                 ? LEVEL_RGB :
	(glyph_on && is_streak_d)                ? streak_colour_d :
	(glyph_on && !is_level_d && !is_streak_d
			  && timer_on_d)                 ? TIMER_RGB :
	in_ui_d                                  ? UI_BG_RGB :
											   bg_d;

always @(posedge clk) begin
	if (!resetn) begin
		glyph_hit_d <= 0;
		is_level_d <= 0;
		is_streak_d <= 0;
		streak_colour_d <= 0;
		src_x_d <= 0;
		bg_d <= 0;
		tuser_d <= 0;
		tvalid_d <= 0;
		timer_on_d <= 0;
		btn_ind_d <= 0;
		in_ui_d <= 0;
	end else if (out_axis_tready) begin
		tvalid_d <= in_axis_tvalid;
		if (fire) begin
			glyph_hit_d <= glyph_hit;
			is_level_d <= is_level;
			is_streak_d <= is_streak;
			streak_colour_d <= streak_colour;
			src_x_d <= src_x;
			bg_d <= in_axis_tdata;
			tuser_d <= in_axis_tuser;
			timer_on_d <= timer_on;
			btn_ind_d <= btn_indicator;
			in_ui_d <= in_ui;
		end
	end
end

always @(posedge clk) begin
	if (!resetn) begin
		blink_cnt <= 0;
		blink_on <= 1'b1;
	end else if (fire) begin
		if (in_axis_tuser[0] && blinking) begin
			if (blink_cnt == 5'd29) begin
				blink_cnt <= 5'd0;
				blink_on <= !blink_on;
			end else begin
				blink_cnt <= blink_cnt + 1'b1;
			end
		end else if (!blinking) begin
			blink_cnt <= 5'd0;
			blink_on <= 1'b1;
		end
	end
end

always @(posedge clk) begin
	if (!resetn) begin
		hcursor <= 0;
		vcursor <= 0;
	end else if (fire) begin
		if (in_axis_tuser[0]) begin
			hcursor <= 1;
			vcursor <= 0;
		end else if (hcursor == SVO_HOR_PIXELS - 1) begin
			hcursor <= 0;
			if (vcursor == SVO_VER_PIXELS - 1)
				vcursor <= 0;
			else
				vcursor <= vcursor + 1;
		end else begin
			hcursor <= hcursor + 1;
		end
	end
end
endmodule
